"""add rental_end_date to user_profiles

Revision ID: 0bd096db5ae8
Revises: e98513ef9f56
Create Date: 2026-05-29 14:21:11.986082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd096db5ae8'
down_revision: Union[str, Sequence[str], None] = 'e98513ef9f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('rental_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'rental_end_date')
    # ### end Alembic commands ###
