"""add user_consents table

Revision ID: e98513ef9f56
Revises: b2c3d4e5f6a7
Create Date: 2026-05-29 14:02:07.676638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98513ef9f56'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terms_agreed', sa.Boolean(), nullable=False),
    sa.Column('privacy_agreed', sa.Boolean(), nullable=False),
    sa.Column('marketing_agreed', sa.Boolean(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_consents_id'), 'user_consents', ['id'], unique=False)
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.create_index(op.f('ix_card_transactions_id'), 'card_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_user_cards_id'), 'user_cards', ['id'], unique=False)
    op.alter_column('user_profiles', 'has_ott',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'has_rental',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'has_rental',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_profiles', 'has_ott',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_user_cards_id'), table_name='user_cards')
    op.drop_index(op.f('ix_card_transactions_id'), table_name='card_transactions')
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_consents_id'), table_name='user_consents')
    op.drop_table('user_consents')
    # ### end Alembic commands ###
